server:
  port: 8801
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: eureka01
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:8888/eureka,http://eureka02:8802/eureka
  server:
    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false