server:
  port: 8802
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: eureka02
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:8888/eureka,http://eureka01:8801/eureka
  server:
    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false